version: "3.9"

services:

  worker: Dockerfile

    build: .

    environment:
    
     - TOKEN = ${TOKEN}
     - ON9BOT_TOKEN = ${ON9BOT_TOKEN}
     - DB_URI = ${DB_URI}
     - OWNER_ID = ${OWNER_ID}
     - API_HASH = ${API_HASH}
     - API_ID = ${API_ID}
     - ADMIN_GROUP_ID = ${ADMIN_GROUP_ID}
     - OFFICIAL_GROUP_ID = ${OFFICIAL_GROUP_ID}
     - WORD_ADDITION_CHANNEL_ID = ${WORD_ADDITION_CHANNEL_ID}
     - VIP = ${VIP}
     - VIP_GROUP = ${VIP_GROUP}
